#En este módulo se generan los ejemplos requeridos utilizando P-Grafos

import pgrafos
import random

def crear_arboles_FS(nombre_archivo, grafo, id_nodo_s):
    grafo_fs = grafo.BFS(id_nodo_s)
    grafo_fs.guardar(nombre_archivo + "_BFS")
    grafo_fs = grafo.DFS_iterativo(id_nodo_s)
    grafo_fs.guardar(nombre_archivo + "_DFSi")
    grafo_fs = grafo.DFS_recursivo(id_nodo_s)
    grafo_fs.guardar(nombre_archivo + "_DFSr")

def crear_arboles_MST(nombre_archivo, grafo):
    grafo_mst = grafo.KruskalI()
    print("El peso total del MST con Kruskal Inv. de " + nombre_archivo + " es: " + grafo_mst[1])
    grafo_mst[0].guardar(nombre_archivo + "_kruskalI")
    grafo_mst = grafo.KruskalD()
    print("El peso total del MST con Kruskal " + nombre_archivo + "  es: " + grafo_mst[1])
    grafo_mst[0].guardar(nombre_archivo + "_kruskalI")
    grafo_mst = grafo.Prim()
    print("El peso total del MST con Prim " + nombre_archivo + "  es: " + grafo_mst[1])
    grafo_mst[0].guardar(nombre_archivo + "_kruskalI")

def crear_dijkstra(nombre_archivo, grafo, s):
    grafo_dijkstra = grafo.Dijkstra(s)
    grafo_dijkstra[0].guardar(nombre_archivo + "_dijkstra_etiquetado")
    grafo_dijkstra[1].guardar(nombre_archivo + "_dijkstra_arbol")

def generar_distancias_aleatorias(grafo, min, max):
    for arista in grafo.aristas:
        arista.definir_propiedad("distancia", random.randint(min, max))

grafo = pgrafos.Grafo.generar_BarbasiAlbert_variante(30, 3)
grafo.guardar("Barbasi-Albert/BarbasiAlbert_variante_30")
crear_arboles_FS("Barbasi-Albert/BarbasiAlbert_variante_30", grafo, 15)
grafo = pgrafos.Grafo.generar_BarbasiAlbert_variante(100, 4)
grafo.guardar("Barbasi-Albert/BarbasiAlbert_variante_100")
crear_arboles_FS("Barbasi-Albert/BarbasiAlbert_variante_100", grafo, 50)
grafo = pgrafos.Grafo.generar_BarbasiAlbert_variante(500, 5)
grafo.guardar("Barbasi-Albert/BarbasiAlbert_variante_500")
crear_arboles_FS("Barbasi-Albert/BarbasiAlbert_variante_500", grafo, 250)

grafo = pgrafos.Grafo.generar_DorogovtsevMendes(30)
grafo.guardar("Dorogovstev-Mendes/DorogovtsevMendes_30")
crear_arboles_FS("Dorogovstev-Mendes/DorogovtsevMendes_30", grafo, 15)
grafo = pgrafos.Grafo.generar_DorogovtsevMendes(100)
grafo.guardar("Dorogovstev-Mendes/DorogovtsevMendes_100")
crear_arboles_FS("Dorogovstev-Mendes/DorogovtsevMendes_100", grafo, 50)
grafo = pgrafos.Grafo.generar_DorogovtsevMendes(500)
grafo.guardar("Dorogovstev-Mendes/DorogovtsevMendes_500")
crear_arboles_FS("Dorogovstev-Mendes/DorogovtsevMendes_500", grafo, 250)

grafo = pgrafos.Grafo.generar_ErdosRenyi(30, 20)
grafo.guardar("Erdos-Renyi/ErdosRenyi_30")
crear_arboles_FS("Erdos-Renyi/ErdosRenyi_30", grafo, 15)
grafo = pgrafos.Grafo.generar_ErdosRenyi(100, 80)
grafo.guardar("Erdos-Renyi/ErdosRenyi_100")
crear_arboles_FS("Erdos-Renyi/ErdosRenyi_100", grafo, 50)
grafo = pgrafos.Grafo.generar_ErdosRenyi(500, 350)
grafo.guardar("Erdos-Renyi/ErdosRenyi_500")
crear_arboles_FS("Erdos-Renyi/ErdosRenyi_500", grafo, 250)

grafo = pgrafos.Grafo.generar_geo_simple(30, 0.1)
grafo.guardar("geografico/geografico_30")
crear_arboles_FS("geografico/geografico_30", grafo, 15)
grafo = pgrafos.Grafo.generar_geo_simple(100, 0.06)
grafo.guardar("geografico/geografico_100")
crear_arboles_FS("geografico/geografico_100", grafo, 50)
grafo = pgrafos.Grafo.generar_geo_simple(500, 0.01)
grafo.guardar("geografico/geografico_500")
crear_arboles_FS("geografico/geografico_500", grafo, 250)

grafo = pgrafos.Grafo.generar_Gilbert(30, 0.3)
grafo.guardar("Gilbert/gilbert_30")
crear_arboles_FS("Gilbert/gilbert_30", grafo, 15)
grafo = pgrafos.Grafo.generar_Gilbert(100, 0.3)
grafo.guardar("Gilbert/gilbert_100")
crear_arboles_FS("Gilbert/gilbert_100", grafo, 50)
grafo = pgrafos.Grafo.generar_Gilbert(500, 0.3)
grafo.guardar("Gilbert/gilbert_500")
crear_arboles_FS("Gilbert/gilbert_500", grafo, 250)

grafo = pgrafos.Grafo.generar_malla(3, 10)
grafo.guardar("malla/malla_30")
crear_arboles_FS("malla/malla_30", grafo, 15)
grafo = pgrafos.Grafo.generar_malla(25, 4)
grafo.guardar("malla/malla_100")
crear_arboles_FS("malla/malla_100", grafo, 50)
grafo = pgrafos.Grafo.generar_malla(25, 20)
grafo.guardar("malla/malla_500")
crear_arboles_FS("malla/malla_500", grafo, 250)

#Dijksta y MST
grafo = pgrafos.Grafo.generar_malla(5,6)
generar_distancias_aleatorias(grafo, 1, 15)
crear_dijkstra("malla/malla_pocos", grafo, 15)
crear_arboles_MST("malla/malla_pocos", grafo)
grafo = pgrafos.Grafo.generar_malla(25, 10)
generar_distancias_aleatorias(grafo, 1, 15)
crear_dijkstra("malla/malla_muchos", grafo)
crear_arboles_MST("malla/malla_muchos", grafo)

grafo = pgrafos.Grafo.generar_BarbasiAlbert_variante(30, 5)
generar_distancias_aleatorias(grafo, 1, 15)
crear_dijkstra("Barbasi-Albert/BarbasiAlbert_variante_pocos", grafo, 15)
crear_arboles_MST("Barbasi-Albert/BarbasiAlbert_variante_pocos", grafo)
grafo = pgrafos.Grafo.generar_BarbasiAlbert_variante(250, 6)
generar_distancias_aleatorias(grafo, 1, 15)
crear_dijkstra("Barbasi-Albert/BarbasiAlbert_variante_muchos", grafo, 30)
crear_arboles_MST("Barbasi-Albert/BarbasiAlbert_variante_muchos", grafo)

grafo = pgrafos.Grafo.generar_DorogovtsevMendes(30)
generar_distancias_aleatorias(grafo, 1, 15)
crear_dijkstra("Dorogovstev-Mendes/DorogovtsevMendes_pocos", grafo, 15)
crear_arboles_MST("Dorogovstev-Mendes/DorogovtsevMendes_pocos", grafo)
grafo = pgrafos.Grafo.generar_DorogovtsevMendes(250)
generar_distancias_aleatorias(grafo, 1, 15)
crear_dijkstra("Dorogovstev-Mendes/DorogovtsevMendes_muchos", grafo, 30)
crear_arboles_MST("Dorogovstev-Mendes/DorogovtsevMendes_muchos", grafo)

grafo = pgrafos.Grafo.generar_ErdosRenyi(30, 30)
generar_distancias_aleatorias(grafo, 1, 15)
crear_dijkstra("Erdos-Renyi/ErdosRenyi_pocos", grafo, 15)
crear_arboles_MST("Erdos-Renyi/ErdosRenyi_pocos", grafo)
grafo = pgrafos.Grafo.generar_ErdosRenyi(250, 200)
generar_distancias_aleatorias(grafo, 1, 15)
crear_dijkstra("Erdos-Renyi/ErdosRenyi_muchos", grafo, 30)
crear_arboles_MST("Erdos-Renyi/ErdosRenyi_muchos", grafo)

grafo = pgrafos.Grafo.generar_geo_simple(30, 0.05)
generar_distancias_aleatorias(grafo, 1, 15)
crear_dijkstra("geografico/geografico_pocos", grafo, 15)
crear_arboles_MST("geografico/geografico_pocos", grafo)
grafo = pgrafos.Grafo.generar_geo_simple(250, 0.05)
generar_distancias_aleatorias(grafo, 1, 15)
crear_dijkstra("geografico/geografico_muchos", grafo, 30)
crear_arboles_MST("geografico/geografico_muchos", grafo)

grafo = pgrafos.Grafo.generar_Gilbert(30, 0.4)
generar_distancias_aleatorias(grafo, 1, 15)
crear_dijkstra("Gilbert/gilbert_pocos", grafo, 15)
crear_arboles_MST("Gilbert/gilbert_pocos", grafo)
grafo = pgrafos.Grafo.generar_Gilbert(250, 0.4)
generar_distancias_aleatorias(grafo, 1, 15)
crear_dijkstra("Gilbert/gilbert_muchos", grafo, 30)
crear_arboles_MST("Gilbert/gilbert_muchos", grafo)
